global:
  templatesdir: "/usr/src/app/amald/reports/tmpl/"
showsamestate: false
loaders:
  gcloudcli: ~
  textfile: 
    path: "/usr/src/app/amald/urls.txt"
summaryintervals:
  - title: "yesterday"
    distancehours: 24
    ansii: "green+h:black"
  - title: "last week"
    distancehours: 168
    ansii: "red+h:black"
  - title: "last month"
    distancehours: 720
    ansii: "blue+h:black"
reports:
  ascii: ~
  mailgun:
    privatekey: "key-aaa"
    domain: "https://api.mailgun.net/v2/mg.domain.com"
    from: "Lockdown Tracker <postmaster@mg.domain.com>"
    to: "Sysadmins <me@domain.com>"
    subj: "Lockdown status report"
storage:
  json:
    path: "/data/data.json" # folder must exist
    recordlimit: 40 # careful: this could truncate an existing file
