activeloaders:
  #gcloudcli: ~
  textfile:
    path: "/usr/src/app/amald/urls.txt"
reports:
  ascii: ~
  mailgun:
    privatekey: "key-e0a7e21bd25805847d63c3eef4762cdf"
    domain: "https://api.mailgun.net/v2/mg.rehabstudio.com"
    from: "Lockdown Tracker <postmaster@mg.rehasbtudio.com>"
    to: "Sysadmins <peter.mcconnell@rehabstudio.com>"
    subj: "Lockdown status report"
storage:
  json:
    path: "/usr/src/app/amald/data/data.json" # folder must exist
    recordlimit: 40 # careful: this could truncate an existing file