activeloaders:
  gcloudcli: ~
  textfile:
    path: "/usr/src/app/amald/urls.txt"
reports:
  ascii: ~
  mailgun:
    privatekey: "key-aaa"
    domain: "https://api.mailgun.net/v2/mg.domain.com"
    from: "Lockdown Tracker <postmaster@mg.domain.com>"
    to: "Sysadmins <me@domain.com>"
    subj: "Lockdown status report"
storage:
  json:
    path: "/data/data.json" # folder must exist
    recordlimit: 40 # careful: this could truncate an existing file
